/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TicTacToePackage;

import javax.swing.JButton;



/**
 *
 * @author malil6384
 */
public class TicTacToeGame extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToeGame
     */
    public TicTacToeGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnSlot1 = new javax.swing.JButton();
        btnSlot2 = new javax.swing.JButton();
        btnSlot3 = new javax.swing.JButton();
        btnSlot4 = new javax.swing.JButton();
        btnSlot5 = new javax.swing.JButton();
        btnSlot6 = new javax.swing.JButton();
        btnSlot7 = new javax.swing.JButton();
        btnSlot8 = new javax.swing.JButton();
        btnSlot9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 100, 200));
        lblTitle.setText("Tic Tac Toe!");

        btnSlot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot1ActionPerformed(evt);
            }
        });

        btnSlot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot2ActionPerformed(evt);
            }
        });

        btnSlot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot3ActionPerformed(evt);
            }
        });

        btnSlot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot4ActionPerformed(evt);
            }
        });

        btnSlot5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot5ActionPerformed(evt);
            }
        });

        btnSlot6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot6ActionPerformed(evt);
            }
        });

        btnSlot7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot7ActionPerformed(evt);
            }
        });

        btnSlot8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot8ActionPerformed(evt);
            }
        });

        btnSlot9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlot9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSlot4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlot5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSlot7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSlot8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSlot9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSlot6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSlot4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(btnSlot5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSlot6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSlot8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSlot9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSlot7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(124, 124, 124))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSlot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot1ActionPerformed
        //Checking if turn is true or false, updating text depending on result
        play();
        updateText(btnSlot1, slot1);
    }//GEN-LAST:event_btnSlot1ActionPerformed

    private void btnSlot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot2ActionPerformed
        //Checking if turn is true or false, updating text depending on result
        play();
        updateText(btnSlot2, slot2);
    }//GEN-LAST:event_btnSlot2ActionPerformed

    private void btnSlot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot3ActionPerformed
        //Checking if turn is true or false, updating text depending on result
        play();
        updateText(btnSlot3, slot3);
    }//GEN-LAST:event_btnSlot3ActionPerformed

    private void btnSlot6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot6ActionPerformed
        //Checking if turn is true or false, updating text depending on result
        play();
        updateText(btnSlot6, slot6);
    }//GEN-LAST:event_btnSlot6ActionPerformed

    private void btnSlot5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot5ActionPerformed
        //Checking if turn is true or false, updating text depending on result
        play();
        updateText(btnSlot5, slot5);
    }//GEN-LAST:event_btnSlot5ActionPerformed

    private void btnSlot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot4ActionPerformed
        //Checking if turn is true or false, updating text depending on result
        play();
        updateText(btnSlot4, slot4);
    }//GEN-LAST:event_btnSlot4ActionPerformed

    private void btnSlot9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot9ActionPerformed
        //Checking if turn is true or false, updating text depending on result
        play();
        updateText(btnSlot9, slot9);
    }//GEN-LAST:event_btnSlot9ActionPerformed

    private void btnSlot8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot8ActionPerformed
        //Checking if turn is true or false, updating text depending on result
        play();
        updateText(btnSlot8, slot8);
    }//GEN-LAST:event_btnSlot8ActionPerformed

    private void btnSlot7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlot7ActionPerformed
        //Checking if turn is true or false, updating text depending on result
        play();
        updateText(btnSlot7, slot7);
    }//GEN-LAST:event_btnSlot7ActionPerformed

    //Variable declaration
    public int slot1;
    public int slot2;
    public int slot3;
    public int slot4;
    public int slot5;
    public int slot6;
    public int slot7;
    public int slot8;
    public int slot9;
    //Number to decide player's turn
    public int turnNum = 0;
    //Boolean to decide what to set text on buttons to
    public boolean turn;
    //Winner variable
    public int winner;
    //Method creation
    public void play(){
        //Checks if the turnNum is equal or odd
        if(turnNum % 2 == 0){
            turn = true;
            
        } else {
            turn = false;
            
        }
        
        //Increase turn int for next player's turn
        turnNum++;
    }
    
    public void updateText(JButton btn, int slot){
        if(turn == true){
            btn.setText("X");   
            slot = 1;
        } else {
            btn.setText("O");
            slot = 2;
        }
        
    }
    
    public void checkWin(){
        if((slot1 == 1 && slot2 == 1 && slot3 == 1) || 
            (slot1 == 1 && slot4 == 1 && slot7 == 1) ||
                (slot1 == 1 && slot5 == 1 && slot9 == 1)){
            
        }
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToeGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSlot1;
    private javax.swing.JButton btnSlot2;
    private javax.swing.JButton btnSlot3;
    private javax.swing.JButton btnSlot4;
    private javax.swing.JButton btnSlot5;
    private javax.swing.JButton btnSlot6;
    private javax.swing.JButton btnSlot7;
    private javax.swing.JButton btnSlot8;
    private javax.swing.JButton btnSlot9;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
